export interface Platform {
  id: string;
  name: string;
  emoji: string;
  type: "appx" | "pinnacle" | "unacademy" | "vidcrypt" | "kgs" | "chandx" | "hranker";
  domain: string;
  supportsVideo: boolean;
  supportsPDF: boolean;
  supportsTest: boolean;
  loginRequired: boolean;
  status?: "active" | "down" | "soon";
  appKey?: string;
  hardcodedCourses?: { id: string; name: string }[];
  hrankerSubdomain?: string;
  hrankerApiBase?: string;
}

export const PLATFORMS: Platform[] = [
  // ─── No Login Required ───────────────────────────────────────────
  {
    id: "chandra",
    name: "Chandra Institute",
    emoji: "🏛️",
    type: "appx",
    domain: "chandraclasses.in",
    supportsVideo: true,
    supportsPDF: false,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "selectionway",
    name: "Selection Way",
    emoji: "🎯",
    type: "appx",
    domain: "api.appx.ac",
    appKey: "selectionway",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: true,
    loginRequired: false,
    status: "active",
    hardcodedCourses: [
      { id: "698481c9fdd21a8a2d18ac5b", name: "Selection Batch-5 (Gagan Pratap Sir)" },
      { id: "698481d9fdd21a8a2d18ac76", name: "Maths Special-5 (Gagan Pratap Sir)" },
      { id: "699eb686a2b1ae04330b857f", name: "Railway Foundation Batch-3 (Gagan Pratap Sir)" },
      { id: "69ae9daca2b1ae04337afa9a", name: "SSC Selection Batch (Gagan Pratap Sir)" },
      { id: "69b2f1e3a2b1ae04338bc1d2", name: "SSC CGL 2026 Complete Batch" },
      { id: "69c4a8f1b2c3de05449cd2e3", name: "Railway NTPC 2026 Batch" },
    ],
  },
  {
    id: "pinnacle",
    name: "SSC Pinnacle",
    emoji: "⭐",
    type: "pinnacle",
    domain: "api.pinnacle.ac",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "ifas",
    name: "IFAS Online",
    emoji: "📚",
    type: "appx",
    domain: "ifasonline.com",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "civilguruji",
    name: "Civil Guruji",
    emoji: "🏛️",
    type: "appx",
    domain: "civilguruji.in",
    supportsVideo: true,
    supportsPDF: false,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "tnc",
    name: "TNC Patna",
    emoji: "🔒",
    type: "appx",
    domain: "tncpatna.com",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "dams",
    name: "DAMS Delhi",
    emoji: "🏛️",
    type: "appx",
    domain: "damsdelhi.com",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "career",
    name: "Career Endeavour",
    emoji: "🚀",
    type: "appx",
    domain: "careerendeavour.in",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "barrack",
    name: "Barrack Buddy",
    emoji: "🎯",
    type: "appx",
    domain: "barrackbuddy.com",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "taiyari",
    name: "Taiyari Karlo",
    emoji: "📖",
    type: "appx",
    domain: "taiyarikarlo.in",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "unacademy",
    name: "Unacademy",
    emoji: "🎓",
    type: "unacademy",
    domain: "unacademy.com",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "jrfadda",
    name: "JRF Adda",
    emoji: "🎯",
    type: "appx",
    domain: "jrfadda.com",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "verbalmaths",
    name: "Verbal Maths",
    emoji: "📐",
    type: "appx",
    domain: "verbalmaths.in",
    supportsVideo: true,
    supportsPDF: false,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "cdsjourney",
    name: "CDS Journey",
    emoji: "⚔️",
    type: "appx",
    domain: "cdsjourney.in",
    supportsVideo: true,
    supportsPDF: false,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "futurekul",
    name: "FutureKul",
    emoji: "✨",
    type: "appx",
    domain: "futurekul.com",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "targetboard",
    name: "Target Board",
    emoji: "🎯",
    type: "appx",
    domain: "targetboard.co",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "appx",
    name: "AppX (No Login)",
    emoji: "📱",
    type: "appx",
    domain: "api.appx.ac",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: true,
    loginRequired: false,
    status: "active",
  },
  {
    id: "kgs",
    name: "KGS (No Login)",
    emoji: "📘",
    type: "kgs",
    domain: "kgs.ac",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  // ─── VidCrypt Platforms ───────────────────────────────────────────
  {
    id: "eduteria",
    name: "Eduteria",
    emoji: "🎓",
    type: "vidcrypt",
    domain: "eduteria.in",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "utkarsh",
    name: "Utkarsh",
    emoji: "📚",
    type: "vidcrypt",
    domain: "utkarsh.com",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "down",
  },
  {
    id: "amanabarkha",
    name: "Learn with Aman Barkha",
    emoji: "🌟",
    type: "vidcrypt",
    domain: "amanabarkha.com",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "examfodu",
    name: "ExamFodu",
    emoji: "📝",
    type: "vidcrypt",
    domain: "examfodu.com",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "physicslinx",
    name: "Physics Linx",
    emoji: "⚡",
    type: "vidcrypt",
    domain: "physicslinx.com",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "soon",
  },
  {
    id: "kautilyags",
    name: "Kautilya GS",
    emoji: "📜",
    type: "vidcrypt",
    domain: "kautilyags.com",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "soon",
  },
  {
    id: "sahitya",
    name: "Sahitya Classes",
    emoji: "📖",
    type: "vidcrypt",
    domain: "sahityaclasses.in",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "chemdias",
    name: "Chemistry Dias",
    emoji: "🧪",
    type: "vidcrypt",
    domain: "chemistrydias.com",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "transeasy",
    name: "Trans Easy",
    emoji: "🔤",
    type: "vidcrypt",
    domain: "transeasy.in",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "officeradda",
    name: "Officer Adda v2",
    emoji: "🎖️",
    type: "vidcrypt",
    domain: "officeradda.in",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "ics",
    name: "ICS Coaching Centre",
    emoji: "🏫",
    type: "vidcrypt",
    domain: "icscoaching.in",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "dslkrantikari",
    name: "DSL Krantikari",
    emoji: "✊",
    type: "vidcrypt",
    domain: "dslkrantikari.com",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "mindmap",
    name: "MindMap",
    emoji: "🧠",
    type: "vidcrypt",
    domain: "mindmap.ac",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
  {
    id: "qualityedu",
    name: "Quality Education",
    emoji: "🌟",
    type: "vidcrypt",
    domain: "qualityeducation.in",
    supportsVideo: true,
    supportsPDF: true,
    supportsTest: false,
    loginRequired: false,
    status: "active",
  },
];

export function getPlatform(id: string): Platform | undefined {
  return PLATFORMS.find((p) => p.id === id);
}

export function getPlatformsByCategory(loginRequired: boolean): Platform[] {
  return PLATFORMS.filter((p) => p.loginRequired === loginRequired);
}

export const NO_LOGIN_PLATFORMS = PLATFORMS.filter(
  (p) => !p.loginRequired && p.type !== "vidcrypt" && p.type !== "hranker",
);
export const VIDCRYPT_PLATFORMS = PLATFORMS.filter(
  (p) => p.type === "vidcrypt",
);
export const LOGIN_PLATFORMS = PLATFORMS.filter(
  (p) => p.loginRequired || p.type === "hranker",
);
